### ISSUE TITLE
Move ember-template-lint to peerDependencies?

### ISSUE THREAD

**Issue by rwjblue** [psbanka/eslint-plugin-hbs#25]
`eslint-plugin-hbs` currently has a direct dependency on `ember-template-lint`, but with the upcoming release of `ember-template-lint@1.0.0` having our own version as a direct dependency of `eslint-plugin-hbs` means that this eslint plugin cannot interoperate with _either_ `ember-template-lint@1` or `ember-template-lint@0.8`. 

Now, we _could_ solve this via a "standard" major version bump (keeping the direct dep), but I think perhaps a better long term solution would be to:

1. move `ember-template-lint` into both `peerDependencies` and `devDependencies`
2. lazily require `ember-template-lint` [here](https://github.com/psbanka/eslint-plugin-hbs/blob/b3b6447339ad2081f9d8cda2667e3dd8daaf61f9/lib/rules/check-hbs-template-literals.js#L55) and report an error if not found
3. bump majors (it still is a "breaking" change to require the project to have the dependency I think)
4. 💸 profit

What do you think?

**Comment by rwjblue** [comment]
@psbanka - What do you think?

**Comment by amk221** [comment]
@psbanka hi 👋 can we get an update on this one please? thanks!

**Comment by psbanka** [comment]
Sorry, y'all. Yes. I've been away from this for quite a while. Will take care of this.

**Comment by amk221** [comment]
Hi, just checking in - it's been 3 months. What's the plan :D

**Comment by psbanka** [comment]
Sorry again for the delay. I have made the changes suggested and released a new version.
